// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use process.env (not env()) so the config file loads when DATABASE_URL is absent
    // (e.g. Docker build). migrate deploy still requires DATABASE_URL at runtime.
    url: process.env.DATABASE_URL,
  },
});
